### ISSUE TITLE
Join Message Dosen't Show

### ISSUE THREAD

**Issue by Crypt97** [ethaniccc/SlapperPlayerCount#10]
the plugin does not print out connected to the server

NO Plugin:
xyz connected to the server

Plugin:
Nothing :s

**Comment by ethaniccc** [comment]
Are you 100% sure that this the cause of my plugin and not anything else? As shown in the screenshot on the README, the join message still shows.

**Comment by Crypt97** [comment]
when it is in it does not appear and when I remove it the text of the connection is displayed.

README image not the updated version, i didn't have a problem with the old one.

**Comment by ethaniccc** [comment]
![Screenshot_20200521-111826](https://user-images.githubusercontent.com/59127626/82574314-e503a180-9b54-11ea-84a0-8a473c9f3a4c.png)
Still works for me though, try making a server without any plugins besides SlapperPlayerCount and test it.

**Comment by Crypt97** [comment]
hmm, Dragons minigame and your plugin conflict join message.
