### ISSUE TITLE
Request: Add Knockback (For Fun Feature)

### ISSUE THREAD

**Issue by VultureMCPE** [ethaniccc/SlapperPlayerCount#12]
Add a whitelist option and make the reason configurable like if it’s whitelisted add a option for the message like the reason why it’s whiteslisted!, also maybe adding a option like if the server is whitelisted or offline make it to where when they hit the slapper it knocks the player back make the knock back configurable, and make it to where if they tap it several times it’ll throw em back further and further

**Comment by ethaniccc** [comment]
>  if it’s whitelisted add a option for the message like the reason why it’s whiteslisted!

Unfortunately, I can't query the whitelist reason, sorry for that!

> if the server is whitelisted or offline make it to where when they hit the slapper it knocks the player back make the knock back configurable, and make it to where if they tap it several times it’ll throw em back further and further

I'll consider adding this to the config as a "For Fun" option, thanks for the suggestion!

**Comment by ethaniccc** [comment]
Due to a certain event not being runned when a Slapper entity is hit, I will have to put this as a "wontfix" for now. However, I will still keep this issue open.
