### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by mikeygio10** [ethaniccc/SlapperPlayerCount#13]
So I cant get the plugin working it loads but there is no config and no error msg

**Comment by mikeygio10** [comment]
Ok got it but not a big bug but the config generates after you make a slapper

**Comment by ethaniccc** [comment]
The config is not implemented properly yet so rip

**Comment by ethaniccc** [comment]
There has been an attempted fix in the latest dev version, please test it in your spare time: https://poggit.pmmp.io/r/90017/CrossOnlineCount_dev-26.phar
