### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by x-lIlIlIlIl** [ethaniccc/SlapperPlayerCount#17]
When i do /slapper create human Factions{line}server:104.194.10.91:19235 and /slapper create human SkyBlock{line}server:104.194.10.91:19240
it says server offline
but when i do it for my kitpvp/hub server it works fine
@ethaniccc

**Comment by AllanWinters** [comment]
You must write in your World name, not your IP Address served

**Example**:
/slapper create human SkyBlock{line}world:Your World Name

**Sample Mine:**
/slapper create human Survival{line}world:Survival

**Hope this helps**

**Comment by Weissnix4711** [comment]
Nah, the world player count works fine. I can confirm though that there is an issue with server player count in the latest update.

**Comment by ethaniccc** [comment]
Should be fixed in the latest dev build, if you still are having this issue, please comment on this issue :)
