### ISSUE TITLE
Server offline.

### ISSUE THREAD

**Issue by DramaLvl1** [ethaniccc/SlapperPlayerCount#19]
In the new Update the Server Count is broken I think.
If I write /slapper spawn human Server{line}server:server.ip:19132
It says that the Server is offline . in the 2.1.0 it still works but now not anymore

**Comment by Weissnix4711** [comment]
Can confirm this is an issue.

Tested the plugin on my lobby server. Plugin version 2.1.3 on PMMP 3.15.1 and all my servers showed as offline.

My servers (excluding the lobby on which this plugin runs) are a combination of vanilla BDS and ElementZero, but none show as online.

Only servers are affected, not worlds.

**Comment by mrpwes** [comment]
I have the same problem but I don't know where exactly the error

**Comment by nokarin-dev** [comment]
Im use the plugin on my lobby but my server show offline

**Comment by ethaniccc** [comment]
Sorry for late response, I barely check this repository anymore.
This should be fixed in dev-builds, and once Slapper updates I will make a release.

If you are still having issues comment on this issue :)

**Comment by yBriisMC** [comment]
yes it is with the same bug
