### ISSUE TITLE
Crash on SlapperCreateEvent

### ISSUE THREAD

**Issue by youngjmc** [ethaniccc/SlapperPlayerCount#2]
The plugin still crashes

**Comment by ethaniccc** [comment]
Can you give me the error log?

**Comment by ethaniccc** [comment]
I think I know what you mean. When you create the slapper it returns you with Internal Server Error. I am now working on this.

**Comment by ethaniccc** [comment]
You can download the latest version here: https://poggit.pmmp.io/r/86558/CrossOnlineCount_dev-4.phar

**Comment by ethaniccc** [comment]
accidently closed
