### ISSUE TITLE
Shows Server offline

### ISSUE THREAD

**Issue by youngjmc** [ethaniccc/SlapperPlayerCount#3]
it shows server offline even though the server is online

**Comment by youngjmc** [comment]
enable-query=on
enable-rcon=off

**Comment by ethaniccc** [comment]
Does the server you are trying to query have the same IP as the server you're querying it from?
If it does, let's say I have 2 servers on the same IP, instead of using my network IP, I would use 127.0.0.1:(port)

**Comment by ethaniccc** [comment]
I will close this issue for now, if it still says "Server Offline", feel free to comment on this issue, and I will re-open it

**Comment by MrJhon2** [comment]
I'm having the same problem
