### ISSUE TITLE
Server offilne

### ISSUE THREAD

**Issue by MrJhon2** [ethaniccc/SlapperPlayerCount#4]
Good whenever I use /slapper spawn human Factions Server IP:PORT it always says that it is offline, but if I just put in /slapper spawn human IP:PORT it shows the amount of players, could you help me?
And every time I try to spawn another normal slapper without any IP:PORT it gives the following error.

PocketMine-MP Crash Dump Fri May 15 12:34:11 -03 2020

Error: Undefined offset: 1
File: plugins/CrossOnlineCount_dev-5.phar/src/ethaniccc/CrossOnlineCount/Main
Line: 68
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CrossOnlineCount v2

Code:
[59]         return self::$instance;
[60]     }
[61] 
[62]     public function updateSlapper(){
[63]       foreach($this->getServer()->getLevels() as $level) {
[64] 			  foreach($level->getEntities() as $entity) {
[65] 				  if(!empty($entity->namedtag->getString("server", ""))) {
[66]             $server = explode(":", $entity->namedtag->getString("server", ""));
[67]             if($server[0] === Internet::getIp()) $server[0] = "127.0.0.1";
[68] 					  $this->getServer()->getAsyncPool()->submitTask(new QueryServer($server[0], $server[1], $entity->getId()));
[69] 				  }
[70] 			  }
[71] 		  }
[72]     }
[73] 
[74]     public function onSlapperCreate(SlapperCreationEvent $ev) {
[75] 		  $entity = $ev->getEntity();
[76] 		  $lines = explode("\n", $entity->getNameTag());
[77] 		  if($this->isValidIP($lines[0]) or $this->is_valid_domain_name($lines[0])) {
[78] 			  $entity->namedtag->setString("server", $lines[0]);

Backtrace:
#0 plugins/CrossOnlineCount_dev-5.phar/src/ethaniccc/CrossOnlineCount/Main(68): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 1, string[126] phar:///home/minecraft/multicraft/servers/server63/plugins/CrossOnlineCount_dev-, integer 68, array[3])
#1 plugins/CrossOnlineCount_dev-5.phar/src/ethaniccc/CrossOnlineCount/Main(38): ethaniccc\CrossOnlineCount\Main->updateSlapper()
#2 src/pocketmine/scheduler/ClosureTask(61): ethaniccc\CrossOnlineCount\Main->ethaniccc\CrossOnlineCount\{closure}(integer 24710)
#3 src/pocketmine/scheduler/TaskHandler(134): pocketmine\scheduler\ClosureTask->onRun(integer 24710)
#4 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 24710)
#5 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 24710)
#6 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 24710)
#7 src/pocketmine/Server(2143): pocketmine\Server->tick()
#8 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1584): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[44] /home/minecraft/multicraft/servers/server63/, string[52] /home/minecraft/multicraft/servers/server63/plugins/)
#11 src/pocketmine/PocketMine(295): pocketmine\server()
#12 (11): require(string[87] phar:///home/minecraft/multicraft/jar/PocketMine1.14.phar/src/pocketmine/PocketM)

**Comment by ethaniccc** [comment]
Thank you for reporting this issue! I will start looking into why this is happening.

**Comment by MrJhon2** [comment]
Okay, I'll be waiting for the new version.

**Comment by ethaniccc** [comment]
I have made a new update to try and fix the problem. I have tested it on my server and had no issues. If there are any issues, please comment again :D

Also, the new usage is: `/slapper create human (your slapper name){line}(IP:Port)`
(The "{line}" thing is to separate the IP and Port stuff)

(Old)New Download: https://poggit.pmmp.io/r/86898/CrossOnlineCount_dev-9.phar
(Updated)New Download: https://poggit.pmmp.io/r/86899/CrossOnlineCount_dev-10.phar

**Comment by MrJhon2** [comment]
Did you give this error when I tried to add, can you use different ports or does it always have to be 19132?

15.05 18:48:35 [Server] Server thread/CRITICAL ErrorException: "Undefined variable: port" (EXCEPTION) in "plugins/CrossOnlineCount_dev-9.phar/src/ethaniccc/CrossOnlineCount/Main" at line 71
15.05 18:48:35 [Server] Server thread/DEBUG #0 plugins/CrossOnlineCount_dev-9.phar/src/ethaniccc/CrossOnlineCount/Main(71): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[24] Undefined variable: port, string[126] phar:///plugins/CrossOnlineCount_dev-, integer 71, array[4])
15.05 18:48:35 [Server] Server thread/DEBUG #1 plugins/CrossOnlineCount_dev-9.phar/src/ethaniccc/CrossOnlineCount/Main(82): ethaniccc\CrossOnlineCount\Main->updateSlapper()
15.05 18:48:35 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/MethodEventExecutor(42): ethaniccc\CrossOnlineCount\Main->onSlapperCreate(object slapper\events\SlapperCreationEvent)
15.05 18:48:35 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object ethaniccc\CrossOnlineCount\Main, object slapper\events\SlapperCreationEvent)
15.05 18:48:35 [Server] Server thread/DEBUG #4 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object slapper\events\SlapperCreationEvent)
15.05 18:48:35 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(666): pocketmine\event\Event->call()
15.05 18:48:35 [Server] Server thread/DEBUG #6 plugins/Slapper.phar/src/slapper/Main(550): pocketmine\plugin\PluginManager->callEvent(object slapper\events\SlapperCreationEvent)
15.05 18:48:35 [Server] Server thread/DEBUG #7 src/pocketmine/command/PluginCommand(54): slapper\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[7] slapper, array[3])
15.05 18:48:35 [Server] Server thread/DEBUG #8 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[7] slapper, array[5])
15.05 18:48:35 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1807): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[62] slapper create human Factions Miner 1{line}51.81.228.202:19134)
15.05 18:48:35 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2221): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[62] slapper create human Factions Miner 1{line}51.81.228.202:19134)
15.05 18:48:35 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[63] /slapper create human Factions Miner 1{line}51.81.228.202:19134)
15.05 18:48:35 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
15.05 18:48:35 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.05 18:48:35 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
15.05 18:48:35 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.05 18:48:35 [Server] Server thread/DEBUG #16 src/pocketmine/Player(3121): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.05 18:48:35 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.05 18:48:35 [Server] Server thread/DEBUG #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 187.74.64.165 49881, object raklib\protocol\EncapsulatedPacket, integer 0)
15.05 18:48:35 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
15.05 18:48:35 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
15.05 18:48:35 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
15.05 18:48:35 [Server] Server thread/DEBUG #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
15.05 18:48:35 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1589568515.7024)
15.05 18:48:35 [Server] Server thread/DEBUG #24 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
15.05 18:48:35 [Server] Server thread/DEBUG #25 src/pocketmine/Server(1584): pocketmine\Server->start()
15.05 18:48:35 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[44] /, string[52] /plugins/)
15.05 18:48:35 [Server] Server thread/DEBUG #27 src/pocketmine/PocketMine(295): pocketmine\server()
15.05 18:48:35 [Server] Server thread/DEBUG #28 (11): require(string[87] phar:///jar/PocketMine1.14.phar/src/pocketmine/PocketM)
15.05 18:48:36 [Multicraft] Server shut down (running)

**Comment by MrJhon2** [comment]
It worked correctly, thank you very much for your answer and quick solution.

**Comment by ethaniccc** [comment]
:D no problem

**Comment by MrJhon2** [comment]
Hello again, so now when we give the command /slapper spawn human World Store {line} Click here to go to the store. Always from Server offline.
https://user-images.githubusercontent.com/26947228/82092082-f4a36600-96ce-11ea-98a2-eaa1db316c69.png
