### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrJhon2** [ethaniccc/SlapperPlayerCount#7]
Hello again, so now when we give the command /slapper spawn human World Store {line} Click here to go to the store. Always from Server offline.

**Comment by ethaniccc** [comment]
Fixed in latest commit
Download: https://poggit.pmmp.io/r/86910/CrossOnlineCount_dev-15.phar

**Comment by ethaniccc** [comment]
After some testing, it no longer did that for me. If this issue still is happening, please comment again and I will reopen this issue.
