### ISSUE TITLE
Server Domains Refuse To Work

### ISSUE THREAD

**Issue by Crypt97** [ethaniccc/SlapperPlayerCount#9]
/slapper create human Example{line}server.com:19132 NOT WORKING

**Comment by ethaniccc** [comment]
Are you using the dev version, or the release on Poggit? If you're using the dev version, the usage has changed - please read the README.

**Comment by Crypt97** [comment]
Using dev, not working :/ 

**/slapper create human Example{line}server:server.com:19132** - NOT WORKING. :(

**/slapper create human Example{line}world:exampleworld** - WORKING. :)

**Comment by ethaniccc** [comment]
For some reason, server domains aren't working right now. You have to use the direct IP until I find out what is causing this
![Screenshot_20200520-162801](https://user-images.githubusercontent.com/59127626/82494204-38271700-9ab7-11ea-8a25-510b16be5949.png)

**Comment by ethaniccc** [comment]
In the latest (dev) version, I have made a fix for server domains, please test out the dev version on your spare time: https://poggit.pmmp.io/r/90017/CrossOnlineCount_dev-26.phar

**Comment by Crypt97** [comment]
Works, but it floods the console > 

```
array(3) {
  [0]=>
  string(6) "server"
  [1]=>
  string(10) "angelpe.hu"
  [2]=>
  string(5) "19132"
}
array(3) {
  [0]=>
  string(6) "server"
  [1]=>
  string(10) "angelpe.hu"
  [2]=>
  string(5) "19132"
}
array(3) {
  [0]=>
  string(6) "server"
  [1]=>
  string(10) "angelpe.hu"
  [2]=>
  string(5) "19132"
}
```

**Comment by ethaniccc** [comment]
Sorry for that, forgot to remove it! Please check the latest dev-version on Poggit: https://poggit.pmmp.io/ci/ethaniccc/SlapperPlayerCount/CrossOnlineCount
